### ISSUE TITLE
System.AccessViolationException in V8_Net_Proxy_x64.DLL

### ISSUE THREAD

**Issue by 010227leo** [rjamesnw/v8dotnet#24]
My application crashed when i use V8.NET, but i can not catch this exception, help please..

> Framework Version: v4.0.30319
 System.AccessViolationException
   at V8.Net.V8NetProxy.DoIdleNotification(V8.Net.NativeV8EngineProxy*, Int32)
   at V8.Net.V8Engine._WorkerLoop()
   at System.Threading.ExecutionContext.RunInternal(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object, Boolean)
   at System.Threading.ExecutionContext.Run(System.Threading.ExecutionContext, System.Threading.ContextCallback, System.Object)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by 010227leo** [comment]
but the way, V8.NET version is 1.5.19.36

**Comment by rjamesnw** [comment]
You are using an old version that followed a system that was not as efficient. The new system does not use worker threads and instead relies on garbage call-back notifications from V8.  I would strongly suggest to update to the newest version.

**Comment by rjamesnw** [comment]
Just FYI:  The code was all commented out here: https://github.com/rjamesnw/v8dotnet/blob/master/Source/V8.Net/V8Engine_Worker.cs

`V8.Net.V8Engine._WorkerLoop()` should not be in the call stack, so just by that alone I can see you have an old version from over a year ago; give or take. ;)

**Comment by 010227leo** [comment]
Thank you very much, the problem solved!!
